// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ServerDashboardApi.Context;

#nullable disable

namespace ServerDashboardApi.Migrations
{
    [DbContext(typeof(DashBoardContext))]
    [Migration("20260904164553_changeInModels")]
    partial class changeInModels
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ServerDashboardApi.Models.Event", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Severity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Temp")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("ServerDashboardApi.Models.ProxmoxNode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Cores")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RamGb")
                        .HasColumnType("int");

                    b.Property<int>("StorageGb")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ProxmoxNodes");
                });

            modelBuilder.Entity("ServerDashboardApi.Models.Temperture", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BottomFans")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("Temp")
                        .HasColumnType("int");

                    b.Property<string>("TopFans")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Tempertures");
                });

            modelBuilder.Entity("ServerDashboardApi.Models.VirtualMachine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Cores")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProxmoxNodeId")
                        .HasColumnType("int");

                    b.Property<int>("RamGb")
                        .HasColumnType("int");

                    b.Property<double>("StorageGb")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("ProxmoxNodeId");

                    b.ToTable("VirtualMachines");
                });

            modelBuilder.Entity("ServerDashboardApi.Models.VirtualMachine", b =>
                {
                    b.HasOne("ServerDashboardApi.Models.ProxmoxNode", "Node")
                        .WithMany("VirtualMachines")
                        .HasForeignKey("ProxmoxNodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Node");
                });

            modelBuilder.Entity("ServerDashboardApi.Models.ProxmoxNode", b =>
                {
                    b.Navigation("VirtualMachines");
                });
#pragma warning restore 612, 618
        }
    }
}
